routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
// 	return view('welcome');
// });

Auth::routes();

Route::get('/', 'Website\HomeController@index')->name('home');

Route::group(['prefix'=> 'admin', 'namespace'=>'Admin\Auth', 'as'=>'admin.'],function(){

	Route::get('login', 'LoginController@showLoginForm')->name('login');
	Route::post('login', 'LoginController@login');
	Route::post('logout', 'LoginController@logout')->name('logout');

	//password reset routes
	Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
	Route::post('password/reset', 'ResetPasswordController@reset');
	Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');

});
Route::group(['prefix'=> 'admin','middleware'=>'auth:admin', 'namespace'=>'Admin', 'as'=>'admin.'],function(){
	
	//dashboards
	Route::get('/', 'AdminController@index')->name('dashboard');
	Route::get('/changePassword', 'AdminController@changePassword')->name('changePassword');
	Route::post('/update_password', 'AdminController@update_password')->name('update_password');

	//seller
	Route::resource('seller', 'SellerController');
	Route::get('getSellerList', 'SellerController@getSellerList')->name('getSellerList');
	Route::get('repo/{id}', 'SellerController@repo')->name('seller.repo');
	Route::put('updaterepo', 'SellerController@updaterepo')->name('seller.updaterepo');

	Route::get('seller/current_listing/{id}', 'SellerController@current_listing')->name('seller.current_listing');
	Route::get('seller/past_listing/{id}', 'SellerController@past_listing')->name('seller.past_listing');
	Route::get('seller/vehicle_detail/{id}', 'SellerController@vehicle_detail')->name('seller.vehicle_detail');
	Route::get('reports', 'AdminController@reports')->name('reports');
	Route::get('getreports', 'AdminController@getreports')->name('getreports');
	Route::get('report/{id}', 'AdminController@report')->name('report');

	//dealers	
	Route::resource('dealer', 'DealerController');	
	Route::post('dealer/update_profile/{id}', 'DealerController@update_profile')->name('dealer.update_profile');

	Route::get('dealer/edit_profile/{id}', 'DealerController@edit_profile')->name('dealer.edit_profile');
	Route::get('getDealerList', 'DealerController@getDealerList')->name('getDealerList');
	Route::get('dealer/dashboard/{id}', 'DealerController@dashboard')->name('dealer.dashboard');
	Route::get('dealer/submitted_bids/{id}', 'DealerController@submitted_bids')->name('dealer.submitted_bids');
	Route::get('dealer/won_bids/{id}', 'DealerController@won_bids')->name('dealer.won_bids');
	Route::get('dealer/payment_detail/{id}', 'DealerController@payment_detail')->name('dealer.payment_detail');
	Route::get('dealer/cancel_subscription/{id}', 'DealerController@cancel_subscription')->name('dealer.cancel_subscription');
	Route::get('dealer/login_as_dealer/{id}', 'DealerController@login_as_dealer')->name('dealer.login_as_dealer');
	Route::post('dealer/is_approved', 'DealerController@is_approved')->name('dealer.is_approved');
	Route::get('dealer/reported_post/{id}', 'DealerController@reported_post')->name('dealer.reported_post');
	Route::get('/view_bid_detail/{dealer_id}/{id}', 'DealerController@view_bid_detail')->name('dealer.view_bid_detail');
	Route::delete('/removeListing/{dealer_id}/{id}', 'DealerController@removeListing')->name('dealer.removeListing');

	//vehicles
	Route::resource('vehicles', 'VehicleController');
	Route::get('getVehiclesList', 'VehicleController@getVehiclesList')->name('getVehiclesList');	
	Route::get('total_earnings', 'PaymentHistoryController@index')->name('totalEarnings');	
	Route::get('seller_orders', 'PaymentHistoryController@seller_orders')->name('sellerOrders');	
	Route::post('seller_orders_list', 'PaymentHistoryController@seller_orders_list')->name('seller_orders_list');	

	/** site settings **/
	Route::get('/settings','SettingController@index')->name('settings.index');
	Route::post('/updateSettings','SettingController@updateSettings')->name('settings.update');

	Route::resource('makes', 'MakeController');
	Route::get('makeList', 'MakeController@makeList')->name('makes.makeList');

});


// Route::get('/', 'Website\HomeController@index')->name('home');
Route::get('/dealer', 'Website\HomeController@dealer_home')->name('dealer_home');

Route::get('/about_us', 'Website\HomeController@about_us')->name('about_us');
Route::get('/pricing', 'Website\HomeController@pricing')->name('pricing');
Route::get('/contact_us', 'Website\HomeController@contact_us')->name('contact_us');
Route::post('/contactus/sendmail', 'Website\HomeController@contactusMail')->name('contactus.mail');
Route::get('/feedback/{token}', 'Website\HomeController@feedback')->name('feedback');
Route::post('/submitFeedback', 'Website\HomeController@submitFeedback')->name('submitFeedback');

Route::group(['namespace'=>'Website\Auth', 'as'=>'website.dealer.'],function(){

	Route::get('signup', 'RegisterController@showRegistrationForm')->name('showRegistrationForm');
	Route::post('signup', 'RegisterController@register')->name('signup');
	Route::get('thankYou', 'RegisterController@thankYou')->name('thankYou');
	Route::get('login', 'LoginController@showLoginForm')->name('login');
	Route::post('login', 'LoginController@login');
	Route::post('logout', 'LoginController@logout')->name('logout');

	//password reset routes
	Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
	Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');
	Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
	// Route::group(['middleware'=>['signupnotCompleted:dealer']],function(){

	Route::get('verify_email', 'RegisterController@verify_email')->name('verify_email');

	Route::post('emailVerification', 'RegisterController@emailVerification')->name('emailVerification');
	Route::post('resendEmailOtp', 'RegisterController@resendEmailOtp')->name('resendEmailOtp');

	Route::get('membership_plan','MembershipPlanController@membership_plan')->name('membership_plan');
	Route::post('addMembershipPlan', 'MembershipPlanController@addMembershipPlan')->name('addMembershipPlan');
	Route::get('payment_info','MembershipPlanController@payment_info')->name('payment_info');
	Route::post('save_card','MembershipPlanController@save_card')->name('save_card');
	Route::get('not_approved','MembershipPlanController@not_approved')->name('not_approved');
	Route::get('plan_status','MembershipPlanController@plan_status')->name('plan_status');
	// });
});
Route::post('/transaction', 'Website\Auth\RegisterController@transaction')->name('transaction');

Route::get('/vehicle_detail/{token}', 'Website\DealerController@vehicle_detail')->name('dealer.vehicle_detail');
Route::group(['prefix'=> 'dealer','namespace'=>'Website', 'as'=>'dealer.','middleware'=>['auth:dealer','verified','signupnotCompleted:dealer']],function(){

	Route::get('/dashboard', ['middleware' => ['permission:dashboard'],'uses'=>'DealerController@index'])->name('dashboard');
	Route::get('/benefits', 'DealerController@benefits')->name('benefits');
	Route::get('/account_setting', 'DealerController@account_setting')->name('account_setting');
	Route::get('/current_listing', ['middleware' => ['permission:dashboard'],'uses'=>'CurrentListingController@index'])->name('current_listing');
	Route::post('/shareVehicle', ['middleware' => ['permission:dashboard'],'uses'=>'DealerController@shareVehicle'])->name('shareVehicle');
	Route::get('/submitted_bids', ['middleware' => ['permission:submitted_bids'],'uses'=>'DealerBidsController@submitted_bids'])->name('submitted_bids');
	Route::post('/submitABid', ['middleware' => ['permission:submit_bid'],'uses'=>'DealerBidsController@submitABid'])->name('submitABid');
	Route::get('/won_bids', ['middleware' => ['permission:won_bids'],'uses'=>'DealerBidsController@won_bids'])->name('won_bids');
	Route::get('/view_bid_detail/{id}', 'DealerBidsController@view_bid_detail')->name('view_bid_detail');
	Route::get('/downloadPdf/{id}', 'DealerBidsController@downloadPdf')->name('downloadPdf');
	Route::get('/edit_profile', 'DealerController@edit_profile')->name('edit_profile');
	Route::post('/update_profile', 'DealerController@update_profile')->name('update_profile');
	Route::post('/update_password', 'DealerController@update_password')->name('update_password');
	Route::get('/notifications', 'NotificationController@index')->name('getNotifications');
	Route::get('/subscription', ['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@index'])->name('subscription');
	Route::post('/update_card', ['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@update_card'])->name('update_card');
	Route::get('/delete_card',['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@delete_card'])->name('delete_card');
	Route::post('/cancel_subscription', ['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@cancel_subscription'])->name('cancel_subscription');
	Route::post('/update_subscription_profile', ['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@update_subscription_profile'])->name('update_subscription_profile');

app/Models/v1/Seller.php
<?php

namespace App\Models\v1;

use Tymon\JWTAuth\Contracts\JWTSubject;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Seller extends Authenticatable implements JWTSubject
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password','email_verified_at','country_code','phone','firebase_android_id','firebase_ios_id','timezone_id','bambora_id','bedge','repo','repo_charged','repo_charge'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

    public function vehicles()
    {
        return $this->hasMany('App\Models\v1\Vehicle','seller_id');
    }

    public function transactions()
    {
        return $this->hasMany('App\Models\v1\SellerTransaction','seller_id');
    }

    public function time_zone(){
        return $this->belongsTo('App\Models\v1\TimeZone','timezone_id');
    }
}

resources/views/admin/sellers/dashboard.blade.php
@section('title','Flipquick | Seller Dashboard')
@extends('admin.layouts.admin-app')
@section('styles')

@endsection
@section('content')
<div class="rightdetailpart">
    <div class="cpbcboxcover">
        <div class="cpbcboxinrpat">
            <div class="textcountbox">
                <div id="shiva"><span class="count">{{$seller->vehicles->where('steps_submitted',8)->count()}}</span></div>            
                <p>Total Vehicles</p>
                <img src="{{ asset('assets/svg/total-vehicles.svg') }}">
            </div>
        </div>
        <div class="cpbcboxinrpat">
            <div class="textcountbox">
                <div id="shiva"><span class="count">@if($seller->earning_amount) {{$seller->earning_amount}} @else 0 @endif </span></div>
                <p>Earning Amount</p>
                <img src="{{ asset('assets/svg/total-income.svg') }}">
            </div>
        </div>
    </div>
    <div class="boxandditboxcover">
        <div class="delspselimabox">
            <div class="wrapper">
                <ul class="tabs">
                    <li><a href="javascript:void(0);" rel="#tabcontent1" class="active">Profile Information</a></li>
                    <li>
                        <div class="pedapclfil">
                            <a href="{{ route('admin.seller.edit',$id) }}" >Edit Profile</a>
                        </div>
                    </li>
                </ul>

                <div class="tab_content_container">
                    <div class="tab_content tab_content_active" id="tabcontent1">
                        <div class="inputcover">
                            <div class="inputwidthsetfull">
                                <div class="profplanboxdit">
                                    <div class="form-group">
                                        <label for="usr"><span>Full Name 
                                        :</span> {{ $seller->first_name.' '.$seller->last_name }} </label>
                                        
                                        <label for="usr"><span>Email Address 
                                        :</span> {{ $seller->email }} </label>
                                        <label for="usr"><span>Phone Number 
                                        :</span> {{ $seller->country_code.'-'.$seller->phone }} </label>

                                    </div>                              
                                </div>                              
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('scripts')
<script>
</script>
@endsection

resources/views/admin/sellers/edit_profile.blade.php
@section('title','Flipquick | Seller Edit Profile')
@extends('admin.layouts.admin-app')
@section('styles')

@endsection
@section('content')
<div class="rightdetailpart">
    <div class="boxandditboxcover">
        <div class="delspselimabox">
            <div class="wrapper">
                <ul class="tabs">
                    <li><a href="javascript:void(0);" rel="#tabcontent1" class=" active">Edit Profile</a></li>
                </ul>

                <div class="tab_content_container">
                    <div class="tab_content tab_content_active" id="tabcontent1">
                        <form id="updateProfileForm" method="post" >
                            @csrf
                            <div class="inputcover">
                                <div class="inputwidthsetbox">
                                    <div class="form-group">
                                        <label for="usr">First Name*</label>
                                        <input type="text" name="first_name" class="form-control" id="" placeholder="Enter First Name" value="{{ $seller->first_name }}">
                                    </div>
                                    <div class="form-group">
                                        <label for="usr">Last Name*</label>
                                        <input type="text" name="last_name" class="form-control" id="" placeholder="Enter Last Name" value="{{ $seller->last_name }}">
                                    </div>
                                </div>
                                <div class="inputwidthsetbox">
                                    <div class="form-group">
                                        <label for="usr">Email Address*</label>
                                        <input type="text" name="email" class="form-control" id="" placeholder="Enter Email Address" value="{{ $seller->email }}">
                                        @error('email')
                                        <label class="error">{{ $message }}</label>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <label for="usr">Phone Number*</label>
                                        <input type="text" name="phone" class="form-control" id="" placeholder="Enter Phone Number" value="{{ $seller->phone }}">
                                        @error('phone')
                                        <label class="error">{{ $message }}</label>
                                        @enderror
                                    </div>
                                </div>
                                <hr>
                                <div class="inputwidthsetbox">                                
                                    <div class="form-group">
                                        <label for="usr">Timezone*</label>
                                        <select name="timezone_id" class="form-control" id="timezone_id" value="{{ old('timezone') }}">
                                            <option>Select Timezone</option>
                                            @foreach($timezones as $timezone)
                                            <option value="{{$timezone->id}}" @if($timezone->id == $seller->timezone_id) selected @endif>{{$timezone->timezone.' ('.$timezone->timezone_name.')'}}</option>
                                            @endforeach
                                        </select>
                                        <label id="placeError" class="error"></label>
                                    </div>                 
                                </div>
                                <div class="cretactboxbtn">
                                    <button type="submit" >UPDATE PROFILE</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAtVAl5jn7PIWC6YSBK-VkIaneaKLIFExM&libraries=places"></script>

<script type="text/javascript">
    $('#updateProfileForm').validate({
        focusInvalid: true,
        ignore: "",
        rules: {
            first_name:{
                required: true
            },
            last_name:{
                required: true
            },
            email:{
                required: true,
                email:true
            },
            phone:{
                required: true,
                number:true
            },
            timezone_id:{
                required: true
            },
        },
        messages: {
            first_name: "Please enter first name",
            last_name:"Please enter last name",
            email:{
                'required':"Please enter email",
                'email':"Invalid email format"
            },
            phone:{
                'required':"Please enter phone",
            },
            timezone_id:"Please select timezone",
        },
        errorPlacement: function(error, element) {
            $(element).css({ "border": "#ffad47 1px solid" });
            $(element).siblings('.help-block').remove();
            if( element.prop('type') == 'select-one' ) {
                $(element).parent().append(error);
            }else if(element.prop('type') == 'checkbox'){
                console.log($(element).parent().siblings('.field_error'));
                $(element).parent().siblings('.field_error').append(error);
            }else{
                error.insertAfter(element);
            }
            if (element.attr("name") == "latitude")
            {
                $('#placeError').html(error);
            }
            if (element.attr("name") == "longitude")
            {
                $('#placeError').html(error);
            }
        },
        submitHandler: function(form) {
            var formData = $(form).serialize();     

            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                method:'PUT',
                url:"{{route('admin.seller.update',$id)}}",
                data:formData,
                beforeSend: function(){
                },
                success:function(data) {
                    switch (data.status) {
                        case true:
                        toastr.success(data.message);
                        location.replace("{{route('admin.seller.show',$id)}}");
                        break;
                        case false:
                        toastr.warning(data.message);
                        break;
                        default:
                        toastr.error("You are not Authorized to access this page");
                        break;
                    }
                },
                complete: function(){
                }
            });
        }
    });
</script>
@endsection

resources/views/admin/sellers/index.blade.php
@section('title','Flipquick | Sellers List')
@extends('admin.layouts.admin-app')
@section('styles')
<style>
/* The container */
.container {
  display: block;
  position: relative;
  padding-left: 35px;
  margin-bottom: 12px;
  cursor: pointer;
  font-size: 22px;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

/* Hide the browser's default radio button */
.container input {
  position: absolute;
  opacity: 0;
  cursor: pointer;
}

/* Create a custom radio button */
.checkmark {
  position: absolute;
  top: 0;
  left: 0;
  height: 25px;
  width: 25px;
  background-color: #eee;
  border-radius: 50%;
}

/* On mouse-over, add a grey background color */
.container:hover input ~ .checkmark {
  background-color: #ccc;
}

/* When the radio button is checked, add a blue background */
.container input:checked ~ .checkmark {
  background-color: #2196F3;
}

/* Create the indicator (the dot/circle - hidden when not checked) */
.checkmark:after {
  content: "";
  position: absolute;
  display: none;
}

/* Show the indicator (dot/circle) when checked */
.container input:checked ~ .checkmark:after {
  display: block;
}

/* Style the indicator (dot/circle) */
.container .checkmark:after {
    top: 9px;
    left: 9px;
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: white;
}
</style>
@endsection
@section('content')
<div class="rightdetailpart">
    <div class="boxandditboxcover">
        <div class="tabledetacoverbox">
            <h3>Sellers</h3>
            <table id="usersTbl" class="table table-striped table-bordered" style="width:100%">
                <thead>
                   <tr>
                        <th>SR</th>
                        <th>Created Date</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Repo</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
<!-- edit modal -->
<div class="modal fade" id="makeEditModal" make="dialog">
 <div class="modal-dialog">

  <!-- Modal content-->
  <div class="modal-content">
   <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">Repo</h4>
</div>
<form id="editMakeFrm">
    @csrf
    @method('PUT')
    <div id="repo"></div>
    <div class="form-group">
        <button type="submit" class="btn btn-default">Update</button>   
    </div>
</form>
</div>
<div class="modal-footer">

</div>
</div>

</div>
</div>
@endsection

@section('scripts')

<script type="text/javascript">
    $(document).ready(function() {
            //GET DATA
            var table = $('#usersTbl').DataTable({
                pageLength: 10,
                processing: true,
                responsive: true,
                serverSide: true,
                order: [],
                lengthMenu: [[10, 50, 100, -1], [10, 50, 100, "All"]],

                ajax: {
                    type: "get",
                    url: "{{ route('admin.getSellerList') }}",
                    data: function ( d ) {
                        d._token = "{{ csrf_token() }}";
                    },
                    complete:function(){
                        if( $('[data-toggle="tooltip"]').length > 0 )
                            $('[data-toggle="tooltip"]').tooltip();
                    }
                },
                columns:[
                { data:'DT_RowIndex',name:'id' },
                { data:'created_at',name:'created_at' },
                { data:'name',name:'name' },
                { data:'email',name:'email' },
                { data:'phone',name:'phone'},
                { data:'repo',name:'repo'},
                { data:'action',name:'action'},
                ],
                columnDefs: [
                {
                    orderable: false,
                        // targets: [0,5],
                        "bSortable": false
                    }
                    ],

                });
    });
    $(document).on('change','input[name="repo"]',function(e){
        if($(this).val() == 1){
          $('#changeRepo').show();
        }else{
          $('#changeRepo').hide();
        }
    });
     $(document).on('change','input[name="repo_charged"]',function(e){
        if($(this).val() == 'charged'){
          $('#repoCharge').show();
        }else{
          $('#repoCharge').hide();
        }
    });
    function changeRepo(id){
        var url = "{{route('admin.seller.repo',':id')}}";
        url = url.replace(':id',id);
        $.ajax({
            url:url,
            type:"GET",
            // data:{id:id},
            success:function(data){
                $('#repo').html(data);
                    $("#makeEditModal").modal('show');

                // if (data.status==true) {              
                //     $("#editMakeName").val(data.data.make);
                //     $("#Makeid").val(data.data.id);
                // } 
            }
        });
    }
$('#editMakeFrm').validate({
    focusInvalid: true,
    ignore: "",
    rules: {
        repoCharge:{
            required: function(element){
              if($('input[name="repo_charged"]').val() == 'charged'){
                return true;
              }
              return false;
            }
        }
    },
    messages: {
        repoCharge: "Please enter make"
    },
    errorPlacement: function(error, element) {
        $(element).css({ "border": "#ffad47 1px solid" });
        $(element).siblings('.help-block').remove();
        if( element.prop('type') == 'select-one' ) {
            $(element).parent().append(error);
        }else if(element.prop('type') == 'checkbox'){
            console.log($(element).parent().siblings('.field_error'));
            $(element).parent().siblings('.field_error').append(error);
        }else{
            error.insertAfter(element);
        }
    },
    submitHandler: function(form) {
        var formData = $(form).serialize();     
        var id      = $("#Makeid").val();

        var url = "{{route('admin.seller.updaterepo')}}";
        $.ajax({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            method:'PUT',
            url:url,
            data:formData,
            beforeSend: function(){
                // $('#updateDoctorBtn').button('loading');
            },
            success:function(data) {
                switch (data.status) {
                    case true:
                    // table.ajax.reload();
                    $("#makeEditModal").modal('hide');
                    toastr.success(data.message);
                    // table.ajax.reload();
                    break;
                    case false:
                    toastr.warning(data.message);
                    break;
                    default:
                    toastr.error("You are not Authorized to access this page");
                    break;
                }
            },
            complete: function(){
                // $('#updateDoctorBtn').button('reset');
            }
        });
    }
});
    </script>
    @endsection

resources/views/admin/sellers/pastvehicle_list_results.blade.php
<?php
$i = 0;
?>
@forelse($data['past_listing'] as $vehicle)
<div class="userimgtextbox">
    @if($vehicle->vehicle_exterior_photos->count() > 0)
    <div class="userimgbox">
        <img src="{{ $vehicle->vehicle_exterior_photos[0]->image }}" alt="">
    </div>
    @endif
    <div class="usertextbox">
        <a href="javascript:void(0)" class="bids_list" data-id="{{ $vehicle->id }}"><h4>{{ $vehicle->year.' '.$vehicle->make.' '.$vehicle->trim.' '.$vehicle->style.' '.$vehicle->model }}</h4></a>
        <p><span class="vehicleVIN">VIN : {{$vehicle->vin_no}}</span> </p>
        <p><span class="vehicleVIN">{{$vehicle->post_type}}</span> </p>

        <p><span>{{ $vehicle->milage }} kms </span><img src="{{ asset('assets/svg/FlipQuick_ellipse_icon.svg') }}" alt=""><span>{{ $vehicle->bids_count }} @if( $vehicle->bids_count>1) Bids @else Bid @endif</span></p>
        <p><span>{{ $vehicle->drive_train }} </span><img src="{{ asset('assets/svg/FlipQuick_ellipse_icon.svg') }}" alt=""><span>{{ ucfirst($vehicle->transmission) }}</span></p>
        @if($vehicle->is_selling)
        <p><span> Sell </span> <img src="{{ asset('assets/svg/FlipQuick_ellipse_icon.svg') }}" alt=""> <span>${{$vehicle->sell_amount}}</span></p>
        @endif
        <p>Vehicle listing removed at {{ $vehicle->expired_at->format('d M, Y h:i A') }} {{ $vehicle->seller->time_zone->timezone_name }}</p>
    </div>
    <div class="listplacebtnbox">
     <a href="javascript:void(0)" class="listingditbtn bids_list" data-id="{{ $vehicle->id }}">LISTING DETAILS</a>
 </div>
</div>
<?php $i++; ?>
@empty
<div class="userimgtextbox">
    <div class="usertextbox">
        <p>No Data Found</p>
    </div>
</div>
@endforelse