routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
// 	return view('welcome');
// });

Auth::routes();

Route::get('/', 'Website\HomeController@index')->name('home');

Route::group(['prefix'=> 'admin', 'namespace'=>'Admin\Auth', 'as'=>'admin.'],function(){

	Route::get('login', 'LoginController@showLoginForm')->name('login');
	Route::post('login', 'LoginController@login');
	Route::post('logout', 'LoginController@logout')->name('logout');

	//password reset routes
	Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
	Route::post('password/reset', 'ResetPasswordController@reset');
	Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');

});
Route::group(['prefix'=> 'admin','middleware'=>'auth:admin', 'namespace'=>'Admin', 'as'=>'admin.'],function(){
	
	//dashboards
	Route::get('/', 'AdminController@index')->name('dashboard');
	Route::get('/changePassword', 'AdminController@changePassword')->name('changePassword');
	Route::post('/update_password', 'AdminController@update_password')->name('update_password');

	//seller
	Route::resource('seller', 'SellerController');
	Route::get('getSellerList', 'SellerController@getSellerList')->name('getSellerList');
	Route::get('repo/{id}', 'SellerController@repo')->name('seller.repo');
	Route::put('updaterepo', 'SellerController@updaterepo')->name('seller.updaterepo');

	Route::get('seller/current_listing/{id}', 'SellerController@current_listing')->name('seller.current_listing');
	Route::get('seller/past_listing/{id}', 'SellerController@past_listing')->name('seller.past_listing');
	Route::get('seller/vehicle_detail/{id}', 'SellerController@vehicle_detail')->name('seller.vehicle_detail');
	Route::get('reports', 'AdminController@reports')->name('reports');
	Route::get('getreports', 'AdminController@getreports')->name('getreports');
	Route::get('report/{id}', 'AdminController@report')->name('report');

	//dealers	
	Route::resource('dealer', 'DealerController');	
	Route::post('dealer/update_profile/{id}', 'DealerController@update_profile')->name('dealer.update_profile');

	Route::get('dealer/edit_profile/{id}', 'DealerController@edit_profile')->name('dealer.edit_profile');
	Route::get('getDealerList', 'DealerController@getDealerList')->name('getDealerList');
	Route::get('dealer/dashboard/{id}', 'DealerController@dashboard')->name('dealer.dashboard');
	Route::get('dealer/submitted_bids/{id}', 'DealerController@submitted_bids')->name('dealer.submitted_bids');
	Route::get('dealer/won_bids/{id}', 'DealerController@won_bids')->name('dealer.won_bids');
	Route::get('dealer/payment_detail/{id}', 'DealerController@payment_detail')->name('dealer.payment_detail');
	Route::get('dealer/cancel_subscription/{id}', 'DealerController@cancel_subscription')->name('dealer.cancel_subscription');
	Route::get('dealer/login_as_dealer/{id}', 'DealerController@login_as_dealer')->name('dealer.login_as_dealer');
	Route::post('dealer/is_approved', 'DealerController@is_approved')->name('dealer.is_approved');
	Route::get('dealer/reported_post/{id}', 'DealerController@reported_post')->name('dealer.reported_post');
	Route::get('/view_bid_detail/{dealer_id}/{id}', 'DealerController@view_bid_detail')->name('dealer.view_bid_detail');
	Route::delete('/removeListing/{dealer_id}/{id}', 'DealerController@removeListing')->name('dealer.removeListing');

	//vehicles
	Route::resource('vehicles', 'VehicleController');
	Route::get('getVehiclesList', 'VehicleController@getVehiclesList')->name('getVehiclesList');	
	Route::get('total_earnings', 'PaymentHistoryController@index')->name('totalEarnings');	
	Route::get('seller_orders', 'PaymentHistoryController@seller_orders')->name('sellerOrders');	
	Route::post('seller_orders_list', 'PaymentHistoryController@seller_orders_list')->name('seller_orders_list');	

	/** site settings **/
	Route::get('/settings','SettingController@index')->name('settings.index');
	Route::post('/updateSettings','SettingController@updateSettings')->name('settings.update');

	Route::resource('makes', 'MakeController');
	Route::get('makeList', 'MakeController@makeList')->name('makes.makeList');

});


// Route::get('/', 'Website\HomeController@index')->name('home');
Route::get('/dealer', 'Website\HomeController@dealer_home')->name('dealer_home');

Route::get('/about_us', 'Website\HomeController@about_us')->name('about_us');
Route::get('/pricing', 'Website\HomeController@pricing')->name('pricing');
Route::get('/contact_us', 'Website\HomeController@contact_us')->name('contact_us');
Route::post('/contactus/sendmail', 'Website\HomeController@contactusMail')->name('contactus.mail');
Route::get('/feedback/{token}', 'Website\HomeController@feedback')->name('feedback');
Route::post('/submitFeedback', 'Website\HomeController@submitFeedback')->name('submitFeedback');

Route::group(['namespace'=>'Website\Auth', 'as'=>'website.dealer.'],function(){

	Route::get('signup', 'RegisterController@showRegistrationForm')->name('showRegistrationForm');
	Route::post('signup', 'RegisterController@register')->name('signup');
	Route::get('thankYou', 'RegisterController@thankYou')->name('thankYou');
	Route::get('login', 'LoginController@showLoginForm')->name('login');
	Route::post('login', 'LoginController@login');
	Route::post('logout', 'LoginController@logout')->name('logout');

	//password reset routes
	Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
	Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');
	Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
	// Route::group(['middleware'=>['signupnotCompleted:dealer']],function(){

	Route::get('verify_email', 'RegisterController@verify_email')->name('verify_email');

	Route::post('emailVerification', 'RegisterController@emailVerification')->name('emailVerification');
	Route::post('resendEmailOtp', 'RegisterController@resendEmailOtp')->name('resendEmailOtp');

	Route::get('membership_plan','MembershipPlanController@membership_plan')->name('membership_plan');
	Route::post('addMembershipPlan', 'MembershipPlanController@addMembershipPlan')->name('addMembershipPlan');
	Route::get('payment_info','MembershipPlanController@payment_info')->name('payment_info');
	Route::post('save_card','MembershipPlanController@save_card')->name('save_card');
	Route::get('not_approved','MembershipPlanController@not_approved')->name('not_approved');
	Route::get('plan_status','MembershipPlanController@plan_status')->name('plan_status');
	// });
});
Route::post('/transaction', 'Website\Auth\RegisterController@transaction')->name('transaction');

Route::get('/vehicle_detail/{token}', 'Website\DealerController@vehicle_detail')->name('dealer.vehicle_detail');
Route::group(['prefix'=> 'dealer','namespace'=>'Website', 'as'=>'dealer.','middleware'=>['auth:dealer','verified','signupnotCompleted:dealer']],function(){

	Route::get('/dashboard', ['middleware' => ['permission:dashboard'],'uses'=>'DealerController@index'])->name('dashboard');
	Route::get('/benefits', 'DealerController@benefits')->name('benefits');
	Route::get('/account_setting', 'DealerController@account_setting')->name('account_setting');
	Route::get('/current_listing', ['middleware' => ['permission:dashboard'],'uses'=>'CurrentListingController@index'])->name('current_listing');
	Route::post('/shareVehicle', ['middleware' => ['permission:dashboard'],'uses'=>'DealerController@shareVehicle'])->name('shareVehicle');
	Route::get('/submitted_bids', ['middleware' => ['permission:submitted_bids'],'uses'=>'DealerBidsController@submitted_bids'])->name('submitted_bids');
	Route::post('/submitABid', ['middleware' => ['permission:submit_bid'],'uses'=>'DealerBidsController@submitABid'])->name('submitABid');
	Route::get('/won_bids', ['middleware' => ['permission:won_bids'],'uses'=>'DealerBidsController@won_bids'])->name('won_bids');
	Route::get('/view_bid_detail/{id}', 'DealerBidsController@view_bid_detail')->name('view_bid_detail');
	Route::get('/downloadPdf/{id}', 'DealerBidsController@downloadPdf')->name('downloadPdf');
	Route::get('/edit_profile', 'DealerController@edit_profile')->name('edit_profile');
	Route::post('/update_profile', 'DealerController@update_profile')->name('update_profile');
	Route::post('/update_password', 'DealerController@update_password')->name('update_password');
	Route::get('/notifications', 'NotificationController@index')->name('getNotifications');
	Route::get('/subscription', ['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@index'])->name('subscription');
	Route::post('/update_card', ['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@update_card'])->name('update_card');
	Route::get('/delete_card',['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@delete_card'])->name('delete_card');
	Route::post('/cancel_subscription', ['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@cancel_subscription'])->name('cancel_subscription');
	Route::post('/update_subscription_profile', ['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@update_subscription_profile'])->name('update_subscription_profile');

resources/views/admin/change_password.blade.php
@section('title','Flipquick | Change Password')
@extends('admin.layouts.admin-app')

@section('content')
<div class="rightdetailpart dashbordscroll">
    <div class="boxandditboxcover">
        <div class="delspselimabox">
            <div class="wrapper">
                <ul class="tabs">
                    <li><a href="javascript:void(0);" rel="#changePassword" class="active">Change Password</a></li>
                </ul>
                <div class="tab_content_container">
                    <div class="tab_content tab_content_active" id="tabcontent1">
                        <form id="resetPasswordForm" method="post" >
                            @csrf
                            <div class="inputcover">
                                <div class="inputwidthsetfull">
                                    <div class="form-group">
                                        <label for="usr">Old Password*</label>
                                        <input type="password" name="password" class="form-control" id="" placeholder="Enter Old Password">
                                    </div>
                                </div>
                                <div class="inputwidthsetbox">
                                    <div class="form-group">
                                        <label for="usr">New Password*</label>
                                        <input type="password" name="newPassword" class="form-control" id="newPassword" placeholder="Enter New Password">
                                    </div>
                                    <div class="form-group">
                                        <label for="usr">Confirm Password*</label>
                                        <input type="password" name="confirm_password" class="form-control" id="" placeholder="Confirm Your Password">
                                    </div>
                                </div>
                                <div class="cretactboxbtn">
                                    <button type="submit" >CHANGE PASSWORD</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAtVAl5jn7PIWC6YSBK-VkIaneaKLIFExM&libraries=places"></script>

<script type="text/javascript">

    $("form#resetPasswordForm").validate({
        rules : {
            "password":{
                required : true
            },
            "newPassword":{
                required : true,
            },
            confirm_password:{
                required: true,
                equalTo:'#newPassword'
            },
        },
        messages : {
            "password":{
                required : "Please provide old password first."
            },
            "newPassword":{
                required : "Please enter new password.",
            },
            confirm_password:{
                'required':"Please confirm your password"
            },
        },
        errorPlacement: function(error, element) {
            $(element).css({ "border": "#ffad47 1px solid" });
            $(element).siblings('.help-block').remove();
            if( element.prop('type') == 'select-one' ) {
                $(element).parent().append(error);
            }else if(element.prop('type') == 'checkbox'){
                console.log($(element).parent().siblings('.field_error'));
                $(element).parent().siblings('.field_error').append(error);
            }else{
                error.insertAfter(element);
            }
        },
        submitHandler: function (form) {
            var input = $("form#resetPasswordForm").find('input');
            var form = $("form#resetPasswordForm").serialize();
            $.ajax({
                url: "{{ route('admin.update_password') }}",
                type: 'POST',
                data: form,
                success:function(data){
                    if(data.status == true){
                        $(input).val('');
                        $("input[name=_token]").val("{{ csrf_token() }}");
                        $("#editProfile").css('color','#3ab772').siblings('button#savePassword').attr('disabled',true);
                        toastr.success(data.message);
                    }else{
                        toastr.error(data.message);
                    }
                }
            });             
        }
    });

</script>
@endsection

resources/views/admin/report.blade.php
@section('title','Flipquick | Account Information')
@extends('admin.layouts.admin-app')
@section('styles')

@endsection
@section('content')
<div class="rightdetailpart">
    <div class="boxandditboxcover">
        <div class="delspselimabox">
            <div class="wrapper">
                <ul class="tabs">
                    <li><a href="javascript:void(0);" rel="#tabcontent1" class="active">Report Information</a></li>
                </ul>

                <div class="tab_content_container">
                    <div class="tab_content tab_content_active" id="tabcontent1">
                        <div class="inputcover">
                            <div class="inputwidthsetfull">
                                <div class="profplanboxdit">
                                    <div class="form-group">
                                        <img src="{{$report->image}}" width="500">
                                        <label for="usr"><span>Subject:</span> {{ $report->title }}</label>
                                        <label for="usr"><span>Description:</span> {{ $report->description }}</label>
                                        <div class="sld boxtitle">
                                       {{-- <h2>Vehicle detail</h2>
                                        <h4>{{ $report->vehicle->year.' '.$report->vehicle->make.' '.$report->vehicle->trim.' '.$report->vehicle->style }}</h4>
                                        <p><span class="vehicleVIN">VIN : {{$report->vehicle->vin_no}}</span> </p>
                                    </div> --}}

                                    </div>                              
                                </div>                              
                            </div>
                            
                        </div>
                    </div>
                    
        </div>
    </div>
</div>
</div>
</div>
@endsection

@section('scripts')

@endsection

resources/views/admin/reports.blade.php
@section('title','Flipquick | Sellers List')
@extends('admin.layouts.admin-app')
@section('styles')

@endsection
@section('content')
<div class="rightdetailpart">
    <div class="boxandditboxcover">
        <div class="tabledetacoverbox">
            <h3>Sellers</h3>
            <table id="usersTbl" class="table table-striped table-bordered" style="width:100%">
                <thead>
                   <tr>
                        <th>SR</th>
                        <th>Subject</th>
                        <th>Created Date</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
@endsection

@section('scripts')

<script type="text/javascript">
    $(document).ready(function() {
            //GET DATA
            var table = $('#usersTbl').DataTable({
                pageLength: 10,
                processing: true,
                responsive: true,
                serverSide: true,
                order: [],
                lengthMenu: [[10, 50, 100, -1], [10, 50, 100, "All"]],

                ajax: {
                    type: "get",
                    url: "{{ route('admin.getreports') }}",
                    data: function ( d ) {
                        d._token = "{{ csrf_token() }}";
                    },
                    complete:function(){
                        if( $('[data-toggle="tooltip"]').length > 0 )
                            $('[data-toggle="tooltip"]').tooltip();
                    }
                },
                columns:[
                { data:'DT_RowIndex',name:'id' },
                { data:'title',name:'title' },
                { data:'created_at',name:'created_at' },
                { data:'action',name:'action'},
                ],
                columnDefs: [
                {
                    orderable: false,
                        // targets: [0,5],
                        "bSortable": false
                    }
                    ],

                });
        });
    </script>
    @endsection

resources/views/admin/seller_vehicle_detail.blade.php
<div class="selectcarboxiner">

    <div class="carsliderbox">
        <div class="gallery-slider">

            <div class="gallery-slider__images sldimgbox">
                <?php  $allImageInner=[]; ?>
                <?php
                $vehicleExteriorPhotos = $vehicle->vehicle_exterior_photos->pluck('image')->toArray();
                $vehicleDamagePhoto = $vehicle->vehicle_damage_photos->pluck('image')->toArray();
                $vehicleInteriorPhoto = $vehicle->vehicle_interior_photos->pluck('image')->toArray();
                $vehicleAllImages = array_merge($vehicleExteriorPhotos,$vehicleInteriorPhoto,$vehicleDamagePhoto);


                $vehicleAllImage = array_merge($vehicleExteriorPhotos,$vehicleInteriorPhoto,$vehicleDamagePhoto);
                $imageHtml = "";

                ?>
                <div>
                    @foreach($vehicleAllImage as $key => $image)
                    <?php $allImageInner[] = ['src' => $image,'thumb'=>$image,'subHtml'=>'']; ?>
                    <div class="item">
                      <div class="img-fill animated-thumbnials">
                        <a href="{{ $image }}">
                            <img src="{{ $image }}" alt="Vehicle {{ $key }}">
                        </a>
                    </div>
                </div>
                <?php 
                $imageHtml .= '<div class="item">
                <div class="img-fill"><img src="'.$image.'" alt="Vehicle '.$key.'"></div>
                </div>'; 
                ?>
                @endforeach
            </div>
        </div>


        <div class="gallery-slider__thumbnails sldthumbnailsbox">
            <div>
                {!! $imageHtml !!}
            </div>
            @if(count($vehicleAllImage) > 0)
            <div class="backnextbtn">
                <button class="prev-arrow slick-arrow nextpribtnbox">
                    BACK
                </button>
                <button class="next-arrow slick-arrow nextpribtnbox">
                    NEXT
                </button>
            </div>                              
            @endif
        </div>
    </div>
</div>

<div class="sldboxtitle">

    <h4>{{ $vehicle->year.' '.$vehicle->make.' '.$vehicle->trim.' '.$vehicle->style }}</h4>
    <p><span class="vehicleVIN">VIN : {{$vehicle->vin_no}}</span> </p>
    <p><span class="vehicleVIN">{{$vehicle->post_type}}</span> </p>
    <p><span>Exterior : {{ $vehicle->exterior_color }}</span> <img src="{{ asset('assets/svg/FlipQuick_ellipse_icon.svg') }}" alt=""> <span>Interior : {{ $vehicle->interior_color }}</span></p>
</div>
<div class="sedoseboxset">
    <ul>
        <li>{{ $vehicle->body_shape }}</li>
        <li>{{ $vehicle->doors }} Doors</li>
        <li>{{ $vehicle->passengers }} Amount Of Seats</li>
    </ul>
</div>
<div class="midetrboxsetiner">
    <ul>
        <li>
            <img src="{{ asset('assets/svg/FlipQuick_milage.svg') }}" alt="">
            <p>Milage <br>{{ $vehicle->milage }} kms</p>
        </li>
        <li>
            <img src="{{ asset('assets/svg/FlipQuick_drive_train.svg') }}" alt="">
            <p>Drive Train <br>{{ $vehicle->drive_train }}</p>
        </li>
        <li>
            <img src="{{ asset('assets/svg/FlipQuick_transmission.svg') }}" alt="">
            <p>Transmission <br>{{ ucfirst($vehicle->transmission) }}</p>
        </li>
        <li>
            <img src="{{ asset('assets/svg/car-engine.svg') }}" alt="">
            <p>Engine <br>{{ ucfirst($vehicle->engine) }}</p>
        </li>
    </ul>
</div>
<div class="tabboxtsetcover">
    <div class="wrapper">
        <ul class="tabs">
            <li><a href="javascript:void(0);" rel="#tabcontent1" class="tab active">options</a></li>
            <li><a href="javascript:void(0);" rel="#tabcontent2" class="tab">additional info</a></li>
            <li><a href="javascript:void(0);" rel="#tabcontent3" class="tab">vehicle condition</a></li>
            <li><a href="javascript:void(0);" rel="#tabcontent4" class="tab">Bids({{$vehicle->bids->count()}})</a></li>
        </ul>

        <div class="tab_content_container">
            <div class="tab_content tab_content_active" id="tabcontent1">
                <p><label>Air Conditioning:</label> {{ ($vehicle->air_conditioning=="1")?'Yes':'No' }}</p>
                <p><label>Navigation System:</label> {{ ($vehicle->navigation_system=="1")?'Yes':'No' }}</p>
                <p><label>Leather Seats:</label> {{ ($vehicle->leather_seats=="1")?'Yes':'No' }}</p>
                <p><label>Sun Roof:</label> {{ ($vehicle->sun_roof=="1")?'Yes':'No' }}</p>
                <p><label>Panoramic Roof:</label> {{ ($vehicle->panoramic_roof=="1")?'Yes':'No' }}</p>
                <p><label>DVD:</label> {{ ($vehicle->dvd=="1")?'Yes':'No' }}</p>
                <p><label>Heated Seats:</label> {{ ($vehicle->heated_seats=="1")?'Yes':'No' }}</p>
                <p><label>AC Seats:</label> {{ ($vehicle->ac_seats=="1")?'Yes':'No' }}</p>
                <p><label>360 Camera:</label> {{ ($vehicle['360_camera']=="1")?'Yes':'No' }}</p>
                <p><label>Engine :</label> {{ $vehicle->engine }}</p>
                <p><label>Cab Type :</label> {{ ($vehicle->style) ? $vehicle->style : '-' }}</p>
                <p><label>Fuel Type : :</label> {{ $vehicle->made_in }}</p>
            </div>

            <div class="tab_content" id="tabcontent2">                                  
                <p><label>After Market Equipment:</label> {{ ($vehicle->after_market_equipment)?$vehicle->after_market_equipment:'-' }}</p>
                <p><label>Original Owner:</label> {{ ($vehicle->original_owner==1)?'Yes':'No' }}</p>
                <p><label>Still Making Monthly Payments:</label> {{ ($vehicle->still_making_monthly_payment=="1")?'Yes':'No' }} </p>
                <p><label>Still Owe:</label> {{ $vehicle->still_own }} </p>
                <p><label>Have Any Accident Claims?:</label> {{ ($vehicle->have_any_accident_record=='1')?'Yes':'No' }} </p>
                <p><label>How Much Are The Claims:</label> {{ ($vehicle->how_much_records > 1)?$vehicle->how_much_records:0 }}</p>
                <p><label>Smoked In:</label> {{ ($vehicle->smoked_in=="1")?'Yes':'No' }}</p>
                <p><label>Modified Exhaust :</label> {{ ($vehicle->modified_exhaust=="1")?'Yes':'No' }}</p>
                <p><label>Sell / Trade :</label> {{ ($vehicle->wantto_sell_or_tradein)?$vehicle->wantto_sell_or_tradein:'-' }}</p>

            </div>  
            <div class="tab_content" id="tabcontent3">                                  
                <p><label>Overall Vehicle Condition:</label> {{ $vehicle->vehicle_condition }}/10</p>
                <p><label>Condition of Front Tires:</label> {{ $vehicle->front_tires_condition }}</p>
                <p><label>Condition of Rear Tires:</label> {{ $vehicle->back_tires_condition }}</p>
                <p><label>Warning Lights In Cluster:</label> {{ ($vehicle->warning_lights_in_clustor=="1")?$vehicle->warning_lights:'No' }}</p>
                <p><label>Mechanical Issues:</label> {{ ($vehicle->mechanical_issues=="1")?'Yes':'No' }}</p>
            </div>
            <div class="tab_content" id="tabcontent4">                                  
                <p><label>{{($vehicle->bids->count() > 1) ? $vehicle->bids->count().' bids' : $vehicle->bids->count().' bid' }} Submitted</label></p>
                <?php $i = 1; ?>
                @forelse($vehicle->bids as $bid)
                <p> {{ $bid->dealer->first_name.' '.$bid->dealer->last_name }} ( {{'$'.$bid->amount}} @if($bid->status) <a href="javascript:void(0)" class="placebidbtn placeBid wonBid">WON</a>  @endif )</p>
                <?php $i++; ?>
                @empty
                <!-- <p><label>No Bids Found</label></p> -->
                @endforelse
            </div>
        </div>
    </div>
</div>
</div>

<script>
    var allImage = {!! json_encode($allImageInner,JSON_UNESCAPED_SLASHES) !!};
</script>

resources/views/admin/vehicle_list_results.blade.php
<?php
$i = 0;
if($current_listing->currentPage() > 1){
    $i = 6*($current_listing->currentPage()-1);
}
?>
@forelse($current_listing as $vehicle)
<div class="userimgtextbox">
    @if($vehicle->vehicle_exterior_photos->count() > 0)
    <div class="userimgbox">
        <img src="{{ $vehicle->vehicle_exterior_photos[0]->image }}" alt="">
    </div>
    @endif
    <div class="usertextbox">
        <a href="javascript:void(0)" class="bids_list" data-id="{{ $vehicle->id }}"><h4>{{ $vehicle->year.' '.$vehicle->make.' '.$vehicle->trim.' '.$vehicle->style.' '.$vehicle->model }}</h4></a>
        <p><span class="vehicleVIN">VIN : {{$vehicle->vin_no}}</span> </p>
        <p><span>{{ $vehicle->milage }} kms </span>
            {{--   <img src="{{ asset('assets/svg/FlipQuick_ellipse_icon.svg') }}" alt=""><span>{{ $vehicle->bids_count }} @if( $vehicle->bids_count>1) Bids @else Bid @endif</span> --}}
        </p>
        <p><span>{{ $vehicle->drive_train }} </span><img src="{{ asset('assets/svg/FlipQuick_ellipse_icon.svg') }}" alt=""><span>{{ ucfirst($vehicle->transmission) }}</span></p>
    </div>
    <div class="hmsboxsetbotbox">
        <p>Current listings will be removed at {{ $vehicle->starts_at }} {{ $vehicle->timezone_name }}</p>
        <ul class="vehicleListTimer" value="{{$vehicle->time_remaining}}">
            <li>
                <h4 id="hours{{$i}}">00</h4>
                <p>Hours</p>
            </li>
            <li>
                <h4 id="minutes{{$i}}">00</h4>
                <p>Minutes</p>
            </li>
            <li>
                <h4 id="seconds{{$i}}">00</h4>
                <p>Seconds</p>
            </li>
        </ul>
    </div>
    <div class="listplacebtnbox">
     <a href="javascript:void(0)" class="listingditbtn bids_list" data-id="{{ $vehicle->id }}">LISTING DETAILS</a>
 </div>
</div>
<?php $i++; ?>
@empty
<div class="userimgtextbox">
    <div class="usertextbox">
        <p>No Data Found</p>
    </div>
</div>
@endif