routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
// 	return view('welcome');
// });

Auth::routes();

Route::get('/', 'Website\HomeController@index')->name('home');

Route::group(['prefix'=> 'admin', 'namespace'=>'Admin\Auth', 'as'=>'admin.'],function(){

	Route::get('login', 'LoginController@showLoginForm')->name('login');
	Route::post('login', 'LoginController@login');
	Route::post('logout', 'LoginController@logout')->name('logout');

	//password reset routes
	Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
	Route::post('password/reset', 'ResetPasswordController@reset');
	Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');

});
Route::group(['prefix'=> 'admin','middleware'=>'auth:admin', 'namespace'=>'Admin', 'as'=>'admin.'],function(){
	
	//dashboards
	Route::get('/', 'AdminController@index')->name('dashboard');
	Route::get('/changePassword', 'AdminController@changePassword')->name('changePassword');
	Route::post('/update_password', 'AdminController@update_password')->name('update_password');

	//seller
	Route::resource('seller', 'SellerController');
	Route::get('getSellerList', 'SellerController@getSellerList')->name('getSellerList');
	Route::get('repo/{id}', 'SellerController@repo')->name('seller.repo');
	Route::put('updaterepo', 'SellerController@updaterepo')->name('seller.updaterepo');

	Route::get('seller/current_listing/{id}', 'SellerController@current_listing')->name('seller.current_listing');
	Route::get('seller/past_listing/{id}', 'SellerController@past_listing')->name('seller.past_listing');
	Route::get('seller/vehicle_detail/{id}', 'SellerController@vehicle_detail')->name('seller.vehicle_detail');
	Route::get('reports', 'AdminController@reports')->name('reports');
	Route::get('getreports', 'AdminController@getreports')->name('getreports');
	Route::get('report/{id}', 'AdminController@report')->name('report');

	//dealers	
	Route::resource('dealer', 'DealerController');	
	Route::post('dealer/update_profile/{id}', 'DealerController@update_profile')->name('dealer.update_profile');

	Route::get('dealer/edit_profile/{id}', 'DealerController@edit_profile')->name('dealer.edit_profile');
	Route::get('getDealerList', 'DealerController@getDealerList')->name('getDealerList');
	Route::get('dealer/dashboard/{id}', 'DealerController@dashboard')->name('dealer.dashboard');
	Route::get('dealer/submitted_bids/{id}', 'DealerController@submitted_bids')->name('dealer.submitted_bids');
	Route::get('dealer/won_bids/{id}', 'DealerController@won_bids')->name('dealer.won_bids');
	Route::get('dealer/payment_detail/{id}', 'DealerController@payment_detail')->name('dealer.payment_detail');
	Route::get('dealer/cancel_subscription/{id}', 'DealerController@cancel_subscription')->name('dealer.cancel_subscription');
	Route::get('dealer/login_as_dealer/{id}', 'DealerController@login_as_dealer')->name('dealer.login_as_dealer');
	Route::post('dealer/is_approved', 'DealerController@is_approved')->name('dealer.is_approved');
	Route::get('dealer/reported_post/{id}', 'DealerController@reported_post')->name('dealer.reported_post');
	Route::get('/view_bid_detail/{dealer_id}/{id}', 'DealerController@view_bid_detail')->name('dealer.view_bid_detail');
	Route::delete('/removeListing/{dealer_id}/{id}', 'DealerController@removeListing')->name('dealer.removeListing');

	//vehicles
	Route::resource('vehicles', 'VehicleController');
	Route::get('getVehiclesList', 'VehicleController@getVehiclesList')->name('getVehiclesList');	
	Route::get('total_earnings', 'PaymentHistoryController@index')->name('totalEarnings');	
	Route::get('seller_orders', 'PaymentHistoryController@seller_orders')->name('sellerOrders');	
	Route::post('seller_orders_list', 'PaymentHistoryController@seller_orders_list')->name('seller_orders_list');	

	/** site settings **/
	Route::get('/settings','SettingController@index')->name('settings.index');
	Route::post('/updateSettings','SettingController@updateSettings')->name('settings.update');

	Route::resource('makes', 'MakeController');
	Route::get('makeList', 'MakeController@makeList')->name('makes.makeList');

});


// Route::get('/', 'Website\HomeController@index')->name('home');
Route::get('/dealer', 'Website\HomeController@dealer_home')->name('dealer_home');

Route::get('/about_us', 'Website\HomeController@about_us')->name('about_us');
Route::get('/pricing', 'Website\HomeController@pricing')->name('pricing');
Route::get('/contact_us', 'Website\HomeController@contact_us')->name('contact_us');
Route::post('/contactus/sendmail', 'Website\HomeController@contactusMail')->name('contactus.mail');
Route::get('/feedback/{token}', 'Website\HomeController@feedback')->name('feedback');
Route::post('/submitFeedback', 'Website\HomeController@submitFeedback')->name('submitFeedback');

Route::group(['namespace'=>'Website\Auth', 'as'=>'website.dealer.'],function(){

	Route::get('signup', 'RegisterController@showRegistrationForm')->name('showRegistrationForm');
	Route::post('signup', 'RegisterController@register')->name('signup');
	Route::get('thankYou', 'RegisterController@thankYou')->name('thankYou');
	Route::get('login', 'LoginController@showLoginForm')->name('login');
	Route::post('login', 'LoginController@login');
	Route::post('logout', 'LoginController@logout')->name('logout');

	//password reset routes
	Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
	Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');
	Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
	// Route::group(['middleware'=>['signupnotCompleted:dealer']],function(){

	Route::get('verify_email', 'RegisterController@verify_email')->name('verify_email');

	Route::post('emailVerification', 'RegisterController@emailVerification')->name('emailVerification');
	Route::post('resendEmailOtp', 'RegisterController@resendEmailOtp')->name('resendEmailOtp');

	Route::get('membership_plan','MembershipPlanController@membership_plan')->name('membership_plan');
	Route::post('addMembershipPlan', 'MembershipPlanController@addMembershipPlan')->name('addMembershipPlan');
	Route::get('payment_info','MembershipPlanController@payment_info')->name('payment_info');
	Route::post('save_card','MembershipPlanController@save_card')->name('save_card');
	Route::get('not_approved','MembershipPlanController@not_approved')->name('not_approved');
	Route::get('plan_status','MembershipPlanController@plan_status')->name('plan_status');
	// });
});
Route::post('/transaction', 'Website\Auth\RegisterController@transaction')->name('transaction');

Route::get('/vehicle_detail/{token}', 'Website\DealerController@vehicle_detail')->name('dealer.vehicle_detail');
Route::group(['prefix'=> 'dealer','namespace'=>'Website', 'as'=>'dealer.','middleware'=>['auth:dealer','verified','signupnotCompleted:dealer']],function(){

	Route::get('/dashboard', ['middleware' => ['permission:dashboard'],'uses'=>'DealerController@index'])->name('dashboard');
	Route::get('/benefits', 'DealerController@benefits')->name('benefits');
	Route::get('/account_setting', 'DealerController@account_setting')->name('account_setting');
	Route::get('/current_listing', ['middleware' => ['permission:dashboard'],'uses'=>'CurrentListingController@index'])->name('current_listing');
	Route::post('/shareVehicle', ['middleware' => ['permission:dashboard'],'uses'=>'DealerController@shareVehicle'])->name('shareVehicle');
	Route::get('/submitted_bids', ['middleware' => ['permission:submitted_bids'],'uses'=>'DealerBidsController@submitted_bids'])->name('submitted_bids');
	Route::post('/submitABid', ['middleware' => ['permission:submit_bid'],'uses'=>'DealerBidsController@submitABid'])->name('submitABid');
	Route::get('/won_bids', ['middleware' => ['permission:won_bids'],'uses'=>'DealerBidsController@won_bids'])->name('won_bids');
	Route::get('/view_bid_detail/{id}', 'DealerBidsController@view_bid_detail')->name('view_bid_detail');
	Route::get('/downloadPdf/{id}', 'DealerBidsController@downloadPdf')->name('downloadPdf');
	Route::get('/edit_profile', 'DealerController@edit_profile')->name('edit_profile');
	Route::post('/update_profile', 'DealerController@update_profile')->name('update_profile');
	Route::post('/update_password', 'DealerController@update_password')->name('update_password');
	Route::get('/notifications', 'NotificationController@index')->name('getNotifications');
	Route::get('/subscription', ['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@index'])->name('subscription');
	Route::post('/update_card', ['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@update_card'])->name('update_card');
	Route::get('/delete_card',['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@delete_card'])->name('delete_card');
	Route::post('/cancel_subscription', ['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@cancel_subscription'])->name('cancel_subscription');
	Route::post('/update_subscription_profile', ['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@update_subscription_profile'])->name('update_subscription_profile');

resources/views/admin/layouts/admin-app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@yield('title','Flipquick | Admin Panel')</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content=""/>
    <meta name="application-name" content="&nbsp;"/>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="apple-touch-icon-precomposed" sizes="57x57" href="{{ asset('favicon/apple-touch-icon-57x57.png') }}" />
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{ asset('favicon/apple-touch-icon-114x114.png') }}" />
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{ asset('favicon/apple-touch-icon-72x72.png') }}" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{{ asset('favicon/apple-touch-icon-144x144.png') }}" />
    <link rel="apple-touch-icon-precomposed" sizes="60x60" href="{{ asset('favicon/apple-touch-icon-60x60.png') }}" />
    <link rel="apple-touch-icon-precomposed" sizes="120x120" href="{{ asset('favicon/apple-touch-icon-120x120.png') }}" />
    <link rel="apple-touch-icon-precomposed" sizes="76x76" href="{{ asset('favicon/apple-touch-icon-76x76.png') }}" />
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="{{ asset('favicon/apple-touch-icon-152x152.png') }}" />
    <link rel="icon" type="image/png" href="{{ asset('favicon/favicon-196x196.png') }}" sizes="196x196" />
    <link rel="icon" type="image/png" href="{{ asset('favicon/favicon-96x96.png') }}" sizes="96x96" />
    <link rel="icon" type="image/png" href="{{ asset('favicon/favicon-32x32.png') }}" sizes="32x32" />
    <link rel="icon" type="image/png" href="{{ asset('favicon/favicon-16x16.png') }}" sizes="16x16" />
    <link rel="icon" type="image/png" href="{{ asset('favicon/favicon-128.png') }}" sizes="128x128" />
    <link href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap.min.css" rel="Stylesheet"></link>
    <link rel="stylesheet" href="{{ asset('css/all.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/custom.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/font-awesome/css/font-awesome.min.css') }}">
    <link href="{{ asset('assets/css/sweetalert.css')}}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{{ asset('css/lightgallery.css') }}">
    

    @yield('styles')
</head>
<body>

    @if(Auth::guard('admin')->check())
    @include('admin.layouts.header')
    <div class="leftbar_rightbarcover">
        @if(!Route::is('admin.dealer.edit_profile')) 
        @include('admin.layouts.left-sidebar')
        @endif
        @yield('content')
    </div>
    @else
    @yield('content')
    @endif


</body>

<script type="text/javascript" src="{{ asset('js/all.js') }}"></script>
<script type="text/javascript" src="{{ asset('assets/js/sweetalert.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/lightgallery.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.13/jquery.mousewheel.min.js"></script>
<script type="text/javascript" src="{{ asset('js/lg-thumbnail.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/lg-fullscreen.min.js') }}"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
<script type="text/javascript" src="https://sachinchoolur.github.io/lightGallery/lightgallery/js/lg-zoom.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
@yield('scripts')
<script type="text/javascript">
    function slider(){
        $(".tabs li a").click(function() {

                // Active state for tabs
                $(".tabs li a").removeClass("active");
                $(this).addClass("active");
                
                // Active state for Tabs Content
                $(".tab_content_container > .tab_content_active").removeClass("tab_content_active").fadeOut(200);
                $(this.rel).fadeIn(500).addClass("tab_content_active");
                
            }); 
        var $imagesSlider = $(".gallery-slider .gallery-slider__images>div"),
        $thumbnailsSlider = $(".gallery-slider__thumbnails>div");

        // images options
        $imagesSlider.slick({
            speed:300,
            slidesToShow:1,
            slidesToScroll:1,
            cssEase:'linear',
            fade:true,
            draggable:false,
            asNavFor:".gallery-slider__thumbnails>div",
            prevArrow:'.gallery-slider__images .prev-arrow',
            nextArrow:'.gallery-slider__images .next-arrow'
        });

        // thumbnails options
        $thumbnailsSlider.slick({
            speed:300,
            slidesToShow:4,
            slidesToScroll:1,
            cssEase:'linear',
            centerMode:true,
            draggable:false,
            focusOnSelect:true,
            asNavFor:".gallery-slider .gallery-slider__images>div",
            prevArrow:'.gallery-slider__thumbnails .prev-arrow',
            nextArrow:'.gallery-slider__thumbnails .next-arrow',
            responsive: [
            {
                breakpoint: 720,
                settings: {
                    slidesToShow: 4,
                    slidesToScroll: 4
                }
            },
            {
                breakpoint: 576,
                settings: {
                    slidesToShow: 3,
                    slidesToScroll: 3
                }
            },
            {
                breakpoint: 350,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 2
                }
            }
            ]
        });

        /*captions*/

        var $caption = $('.gallery-slider .caption');

        // get the initial caption text
        var captionText = $('.gallery-slider__images .slick-current img').attr('alt');
        updateCaption(captionText);

        // hide the caption before the image is changed
        $imagesSlider.on('beforeChange', function(event, slick, currentSlide, nextSlide){
            $caption.addClass('hide');
        });

        // update the caption after the image is changed
        $imagesSlider.on('afterChange', function(event, slick, currentSlide, nextSlide){
            captionText = $('.gallery-slider__images .slick-current img').attr('alt');
            updateCaption(captionText);
        });
        function updateCaption(text) {
            // if empty, add a no breaking space
            if (text === '') {
                text = '&nbsp;';
            }
            $caption.html(text);
            $caption.removeClass('hide');
        }
    }

</script>
</html>
<!-- {{ exit }} -->

resources/views/admin/layouts/header.blade.php
<header>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="headercovercl">
            <div class="">              
                <div class="navbar-header page-scroll">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <!-- <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span> -->
                        <img src="{{ asset('assets/svg/hamburger.svg') }}" alt="" class="hamburgerbtn">
                        <img src="{{ asset('assets/svg/hamburger-close.svg') }}" alt="" class="hamburger_closebtn">
                    </button>
                    <a class="navbar-brand" href="{{ route('admin.dashboard') }}"><img src="{{ asset('assets/svg/logo.svg') }}" alt=""></a>
                </div>
                
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <div class="usermenuboxset">
                      <div>
                        <input type="checkbox" id="check">
                        <label for="check">{{ Auth::user()->name }} <img src="{{ asset('assets/svg/carat-icon.svg') }}"></label>
                        <div class="navbox">
                            <ul>
                                <li> 
                                    <a href="{{ route('admin.changePassword') }}" >Change Password</a>
                                </li>
                                <li> 
                                    <a href="{{ route('admin.logout') }}" onclick="event.preventDefault();
            document.getElementById('logout-form').submit();">Log Out</a>
                                </li>
                            </ul>                       
                        </div>
                        <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                        @csrf
                        </form>
                        @yield('navHeader')
                      </div>
                    </div>
                </div>              
            </div>
        </div>
        
    </nav>
</header>