routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
// 	return view('welcome');
// });

Auth::routes();

Route::get('/', 'Website\HomeController@index')->name('home');

Route::group(['prefix'=> 'admin', 'namespace'=>'Admin\Auth', 'as'=>'admin.'],function(){

	Route::get('login', 'LoginController@showLoginForm')->name('login');
	Route::post('login', 'LoginController@login');
	Route::post('logout', 'LoginController@logout')->name('logout');

	//password reset routes
	Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
	Route::post('password/reset', 'ResetPasswordController@reset');
	Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');

});
Route::group(['prefix'=> 'admin','middleware'=>'auth:admin', 'namespace'=>'Admin', 'as'=>'admin.'],function(){
	
	//dashboards
	Route::get('/', 'AdminController@index')->name('dashboard');
	Route::get('/changePassword', 'AdminController@changePassword')->name('changePassword');
	Route::post('/update_password', 'AdminController@update_password')->name('update_password');

	//seller
	Route::resource('seller', 'SellerController');
	Route::get('getSellerList', 'SellerController@getSellerList')->name('getSellerList');
	Route::get('repo/{id}', 'SellerController@repo')->name('seller.repo');
	Route::put('updaterepo', 'SellerController@updaterepo')->name('seller.updaterepo');

	Route::get('seller/current_listing/{id}', 'SellerController@current_listing')->name('seller.current_listing');
	Route::get('seller/past_listing/{id}', 'SellerController@past_listing')->name('seller.past_listing');
	Route::get('seller/vehicle_detail/{id}', 'SellerController@vehicle_detail')->name('seller.vehicle_detail');
	Route::get('reports', 'AdminController@reports')->name('reports');
	Route::get('getreports', 'AdminController@getreports')->name('getreports');
	Route::get('report/{id}', 'AdminController@report')->name('report');

	//dealers	
	Route::resource('dealer', 'DealerController');	
	Route::post('dealer/update_profile/{id}', 'DealerController@update_profile')->name('dealer.update_profile');

	Route::get('dealer/edit_profile/{id}', 'DealerController@edit_profile')->name('dealer.edit_profile');
	Route::get('getDealerList', 'DealerController@getDealerList')->name('getDealerList');
	Route::get('dealer/dashboard/{id}', 'DealerController@dashboard')->name('dealer.dashboard');
	Route::get('dealer/submitted_bids/{id}', 'DealerController@submitted_bids')->name('dealer.submitted_bids');
	Route::get('dealer/won_bids/{id}', 'DealerController@won_bids')->name('dealer.won_bids');
	Route::get('dealer/payment_detail/{id}', 'DealerController@payment_detail')->name('dealer.payment_detail');
	Route::get('dealer/cancel_subscription/{id}', 'DealerController@cancel_subscription')->name('dealer.cancel_subscription');
	Route::get('dealer/login_as_dealer/{id}', 'DealerController@login_as_dealer')->name('dealer.login_as_dealer');
	Route::post('dealer/is_approved', 'DealerController@is_approved')->name('dealer.is_approved');
	Route::get('dealer/reported_post/{id}', 'DealerController@reported_post')->name('dealer.reported_post');
	Route::get('/view_bid_detail/{dealer_id}/{id}', 'DealerController@view_bid_detail')->name('dealer.view_bid_detail');
	Route::delete('/removeListing/{dealer_id}/{id}', 'DealerController@removeListing')->name('dealer.removeListing');

	//vehicles
	Route::resource('vehicles', 'VehicleController');
	Route::get('getVehiclesList', 'VehicleController@getVehiclesList')->name('getVehiclesList');	
	Route::get('total_earnings', 'PaymentHistoryController@index')->name('totalEarnings');	
	Route::get('seller_orders', 'PaymentHistoryController@seller_orders')->name('sellerOrders');	
	Route::post('seller_orders_list', 'PaymentHistoryController@seller_orders_list')->name('seller_orders_list');	

	/** site settings **/
	Route::get('/settings','SettingController@index')->name('settings.index');
	Route::post('/updateSettings','SettingController@updateSettings')->name('settings.update');

	Route::resource('makes', 'MakeController');
	Route::get('makeList', 'MakeController@makeList')->name('makes.makeList');

});


// Route::get('/', 'Website\HomeController@index')->name('home');
Route::get('/dealer', 'Website\HomeController@dealer_home')->name('dealer_home');

Route::get('/about_us', 'Website\HomeController@about_us')->name('about_us');
Route::get('/pricing', 'Website\HomeController@pricing')->name('pricing');
Route::get('/contact_us', 'Website\HomeController@contact_us')->name('contact_us');
Route::post('/contactus/sendmail', 'Website\HomeController@contactusMail')->name('contactus.mail');
Route::get('/feedback/{token}', 'Website\HomeController@feedback')->name('feedback');
Route::post('/submitFeedback', 'Website\HomeController@submitFeedback')->name('submitFeedback');

Route::group(['namespace'=>'Website\Auth', 'as'=>'website.dealer.'],function(){

	Route::get('signup', 'RegisterController@showRegistrationForm')->name('showRegistrationForm');
	Route::post('signup', 'RegisterController@register')->name('signup');
	Route::get('thankYou', 'RegisterController@thankYou')->name('thankYou');
	Route::get('login', 'LoginController@showLoginForm')->name('login');
	Route::post('login', 'LoginController@login');
	Route::post('logout', 'LoginController@logout')->name('logout');

	//password reset routes
	Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
	Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
	Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');
	Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
	// Route::group(['middleware'=>['signupnotCompleted:dealer']],function(){

	Route::get('verify_email', 'RegisterController@verify_email')->name('verify_email');

	Route::post('emailVerification', 'RegisterController@emailVerification')->name('emailVerification');
	Route::post('resendEmailOtp', 'RegisterController@resendEmailOtp')->name('resendEmailOtp');

	Route::get('membership_plan','MembershipPlanController@membership_plan')->name('membership_plan');
	Route::post('addMembershipPlan', 'MembershipPlanController@addMembershipPlan')->name('addMembershipPlan');
	Route::get('payment_info','MembershipPlanController@payment_info')->name('payment_info');
	Route::post('save_card','MembershipPlanController@save_card')->name('save_card');
	Route::get('not_approved','MembershipPlanController@not_approved')->name('not_approved');
	Route::get('plan_status','MembershipPlanController@plan_status')->name('plan_status');
	// });
});
Route::post('/transaction', 'Website\Auth\RegisterController@transaction')->name('transaction');

Route::get('/vehicle_detail/{token}', 'Website\DealerController@vehicle_detail')->name('dealer.vehicle_detail');
Route::group(['prefix'=> 'dealer','namespace'=>'Website', 'as'=>'dealer.','middleware'=>['auth:dealer','verified','signupnotCompleted:dealer']],function(){

	Route::get('/dashboard', ['middleware' => ['permission:dashboard'],'uses'=>'DealerController@index'])->name('dashboard');
	Route::get('/benefits', 'DealerController@benefits')->name('benefits');
	Route::get('/account_setting', 'DealerController@account_setting')->name('account_setting');
	Route::get('/current_listing', ['middleware' => ['permission:dashboard'],'uses'=>'CurrentListingController@index'])->name('current_listing');
	Route::post('/shareVehicle', ['middleware' => ['permission:dashboard'],'uses'=>'DealerController@shareVehicle'])->name('shareVehicle');
	Route::get('/submitted_bids', ['middleware' => ['permission:submitted_bids'],'uses'=>'DealerBidsController@submitted_bids'])->name('submitted_bids');
	Route::post('/submitABid', ['middleware' => ['permission:submit_bid'],'uses'=>'DealerBidsController@submitABid'])->name('submitABid');
	Route::get('/won_bids', ['middleware' => ['permission:won_bids'],'uses'=>'DealerBidsController@won_bids'])->name('won_bids');
	Route::get('/view_bid_detail/{id}', 'DealerBidsController@view_bid_detail')->name('view_bid_detail');
	Route::get('/downloadPdf/{id}', 'DealerBidsController@downloadPdf')->name('downloadPdf');
	Route::get('/edit_profile', 'DealerController@edit_profile')->name('edit_profile');
	Route::post('/update_profile', 'DealerController@update_profile')->name('update_profile');
	Route::post('/update_password', 'DealerController@update_password')->name('update_password');
	Route::get('/notifications', 'NotificationController@index')->name('getNotifications');
	Route::get('/subscription', ['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@index'])->name('subscription');
	Route::post('/update_card', ['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@update_card'])->name('update_card');
	Route::get('/delete_card',['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@delete_card'])->name('delete_card');
	Route::post('/cancel_subscription', ['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@cancel_subscription'])->name('cancel_subscription');
	Route::post('/update_subscription_profile', ['middleware' => ['permission:subscription_management'],'uses'=>'SubscriptionManagementController@update_subscription_profile'])->name('update_subscription_profile');

app/Http/Controllers/Website/CurrentListingController.php
<?php

namespace App\Http\Controllers\Website;

use App\Helpers\AppHelper;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\v1\Vehicle;
use Carbon\Carbon;
use DB;

class CurrentListingController extends Controller
{
	/** current listing page **/
    public function index(){

		$dealer = auth('dealer')->user();  
		$data['timezone'] 		= $dealer->time_zone->timezone;
		$data['timezone_name'] 	= $dealer->time_zone->timezone_name;
		$appTiming = AppHelper::getCurrentSlotTiming($data['timezone']);

		$data['starts_at'] 		= $appTiming['starts_at_timezone']->format('h:i A');
		$data['ends_at'] 		= $appTiming['ends_at_timezone']->format('h:i A');

        $last_slot_time         = $appTiming['last_slot_start'];
		$data['time_remaining']  = $appTiming['time_remaining'];

        $lat  = $dealer->latitude;
		$long = $dealer->longitude;
		$data['last_wons_bids'] = $dealer->bids()
									// ->where('status',1)
									->whereHas('vehicle',function($query) use ($last_slot_time){
										// $query->where('starts_at',$last_slot_time);
									})
									->get()
									->filter(function ($wonBid) {
										return $wonBid->status == 1;
									})
									->count();

        $data['current_listing'] = Vehicle:://where('starts_at','<',$appTiming['ends_at'])
											// ->where('expired_at','>=',$appTiming['ends_at'])
											with(['vehicle_exterior_photos'=>function($query){
												$query->where('vehicle_exterior_type','front')->select('vehicle_id','vehicle_exterior_type','image');
											},'bids'=>function($query) use ($dealer){
												$query->where('dealer_id',$dealer->id);
											}])
											// ->whereRaw('distance >= '.DB::raw('( 6367 * acos( cos( radians('.$lat.') ) * cos( radians( latitude ) ) * cos( radians( longitude ) - radians('.$long.') ) + sin( radians('.$lat.') ) * sin( radians( latitude ) ) ) )'))
											->withCount('bids')
											->get();

		return view('website.current_listing',compact('data'));
	}
}

app/Http/Controllers/Website/HomeController.php
<?php

namespace App\Http\Controllers\Website;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\v1\Vehicle;
use Notification;
use App\Models\v1\SellerFeedback;
use App\Notifications\SellerFeedbackNotification;
use Mail;
class HomeController extends Controller
{
	/** website home page **/
	public function index(){
	   // echo request()->ip();die();
	   return redirect('https://flipquick.ca');
	    if(request()->ip() == '75.158.175.188' || request()->ip() == '103.251.215.170' || request()->ip() == '27.61.146.240'){
    		return redirect('https://flipquick.ca');
    	}else{
    		return view('welcome');
    	}
	}

	/** website dealer home page **/
	public function dealer_home(){
		$vehicle   = Vehicle::where('id','215')
                                ->first();

            // if($vehicle->bids->count() > 0){
                $token = md5(time());
                $feedback = SellerFeedback::create(['seller_id'=>$vehicle->seller->id,'token'=>$token,'type'=>'highest_bid']);
                $username = $vehicle->seller->first_name.' '.$vehicle->seller->last_name;
                $vehicle->seller->email = 'developer.foremost@gmail.com';
                $vehicle->seller->notify(new SellerFeedbackNotification($feedback,$username));
            // }
            die();
		return view('website.dealer_home');
	}

	/** website aboutus page **/
	public function about_us(){
		return view('website.about_us');
	}

	/** website pricing page **/
	public function pricing(){
		return view('website.pricing');
	}

	/** website pricing page **/
	public function contact_us(){
		return view('website.contact_us');
	}
	/** sending contact us mail **/
	public function contactusMail(Request $request){
		
		Mail::send([], [], function($message) use($request){
		        $message->to(['contact@flipquick.ca'], 'FlipQuick')->subject
		           ('flipquick enquiry');
		        $message->from('contact@flipquick.ca','FlipQuick');
		        $message->setBody('<table>
		        					 <tr>
		        					 	<th>Name</th>
		        					 	<th>'.$request->name.'</th>
		        					 </tr>
		        					  <tr>
		        					 	<th>Phone Number</th>
		        					 	<th>'.$request->phone.'</th>
		        					 </tr>
		        					  <tr>
		        					 	<th>Mail ID</th>
		        					 	<th>'.$request->email.'</th>
		        					 </tr>
		        					 <tr>
		        					 	<th>Subject</th>
		        					 	<th>'.$request->subject.'</th>
		        					 </tr> 
		        					 <tr>
		        					 	<th>Help:</th>
		        					 	<th>'.$request->help.'</th>
		        					 </tr>
		        	             </table>', 'text/html'); 
		     });
		return response()->json(['status' => true,'message' => 'Mail Sent Successfully']);
	}

	/** website pricing page **/
	public function feedback($token){
		if(!$token){

		}
		$feedback = SellerFeedback::where('token',$token)->first();
		return view('website.feedback',compact('feedback'));
	}

	/** website pricing page **/
	public function submitFeedback(Request $request){
		
		$feedback = SellerFeedback::where('token',$request->token)->first();
		$inputs=$request->all();
		unset($inputs['_token']);
		$feedback->update($inputs);
		return view('website.feedback',compact('feedback'));
	}



}

app/Http/Controllers/Website/NotificationController.php
<?php

namespace App\Http\Controllers\Website;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Notification;
use Auth;

class NotificationController extends Controller
{
    public function index(Request $request){

    	$page 					= $request->get('page');
		$notifications 			= Auth::user()
									->notifications()
									->whereIn('type',[
										'App\Notifications\CurrentListingPostedNotification',
										'App\Notifications\WonsbidNotification'
									])
									->paginate(6);

		$notifications->getCollection()->transform(function($notification,$index){
			
			$data 	= $notification->data;

			switch($notification['type']) {

				case 'App\Notifications\CurrentListingPostedNotification':
				$notification['title']            = 'New Listing Posted';
				$notification['message']          = 'Hurry Up, '.$notification['data']['available_vehicle'].' new listings are posted today. Submit your bids before the listings goes away.';
				$notification['tag']              = 'CurrentListingPosted';
				break;

				case 'App\Notifications\WonsbidNotification':
				$notification['title']            = 'Won bid';
				$notification['message']          = 'You won a bid';
				$notification['tag']              = 'WonAbid';
				break;

			}

			return $notification;

		});

		$notificationsData 		= Auth::user()
									->notifications()
									->whereIn('type',[
										'App\Notifications\CurrentListingPostedNotification',
										'App\Notifications\WonsbidNotification'
									])
									->paginate(6);
		$notificationsData->getCollection()->transform(function($notificationsData,$index){
			$notificationsData->markAsRead();
		});

		if ($request->ajax()) {
            $view = view('website.notificationResults',compact('notifications'))->render();
            return response()->json(['html'=>$view]);
        }
		$lastPage = $notifications->lastPage();
		return view('website.notification',compact('notifications','lastPage'));
    }
}

resources/views/website/home.blade.php
@section('title','FlipQuick | Home')
@extends('website.layouts.app')
@section('styles')

@endsection
@section('content')
<div class="container">
	<div class="iamsellerboxset">
		<div class="imgaselldealbox">
			<div class="wrapper">
				<ul class="tabs">
					<li><a href="javascript:void(0);" rel="#tabcontent1" class="tab active">I'm a Seller</a></li>
					<li><a href="{{route('dealer_home')}}" rel="#tabcontent2" class="tab">I'm a Dealership</a></li>	       
				</ul>	    
				<div class="tab_content_container">
					<div class="tab_content tab_content_active" id="tabcontent1">
						<div class="iamseltextbox">
							<h3>In 24 hours, FlipQuick will get you your vehicle's maximum value for free.</h3>
							<p>Download our app today and have dealerships in your area compete for your vehicle.</p>
							<div class="andiosboxbtn">
								<a href="javascript:void(0);">ANDROID</a>
								<a href="javascript:void(0);">IOS</a>
							</div>
							{{-- <a href="{{ route('about_us') }}" class="letnmorlink">Learn more about FlipQuick</a> --}}
						</div>
					</div>	        
					<div class="tab_content" id="tabcontent2">
						<div class="iamseltextbox">
							<h3>Are you a Dealership 
								looking to buy vehicles 
							from local sellers?</h3>
							<p>Get started with FlipQuick to view daily vehicle listings. Submit your best bid and start buying!</p>
							<div class="andiosboxbtn">
								<a href="javascript:void(0);">ANDROID</a>
								<a href="javascript:void(0);">IOS</a>
							</div>
							@if(!(auth()->guard('dealer')->check() && auth()->guard('dealer')->user()->email_verified_at && auth()->guard('dealer')->user()->is_approved))
							<a href="{{ route('website.dealer.signup') }}" class="letnmorlink">Sign Up!</a> 
							@endif
							{{-- <a href="{{ route('about_us') }}" class="letnmorlink">Learn more about FlipQuick</a> --}}
						</div>
					</div>	      
				</div>
			</div>
		</div>
	</div>
	<div class="doworkboxset">
		<h3>How does it work?</h3>
		<ul>
			<li class="divdiconset1">
				<img src="{{ asset('assets/svg/flipquick_get_best_offer.svg') }}" alt="">				
				<h4>List Your Car</h4>
				<p>List your vehicle in <br>a few easy steps.</p>
			</li>
			<li  class="divdiconset2">
				<img src="{{ asset('assets/svg/flipquick_receive_offers.svg') }}" alt="">
				<h4>Receive Offers</h4>
				<p>Each dealership will place one<br> offer (their best offer).</p>
			</li>
			<li>
				<img src="{{ asset('assets/svg/flipquick_list_your_car.svg') }}" alt="">
				<h4>Get Best Offer</h4>
				<p>You will be informed of the highest offer<br> for your vehicle and put in touch with the dealership.</p>
			</li>
		</ul>
	</div>

	<div class="lokselboxcover">
		<div class="lokselboxleft">
			<img src="{{ asset('assets/images/flipquick_seller_app.png') }}" alt="">
		</div>
		<div class="lokselboxright">
			<h3>Looking to sell your car?</h3>
			<p>Install FlipQuick to list your vehicle &<br>
			start receiving offers from dealerships</p>
			<a href="javascript:void(0);">ANDROID</a>
			<a href="javascript:void(0);">IOS</a>
		</div>
	</div>

	
	<div class="benflpboxcover">
		<h3>Benefits of FlipQuick</h3>
		<div class="benflpboxiner">
			<div class="benflpboxiner_icon">
				<img src="{{ asset('assets/svg/safety-icon.svg') }}" alt="">
			</div>
			<div class="benflpboxiner_text">
				<h4>Safety</h4>
				<p>You will only be in touch with a certified dealership. This decreases the chance of harm associated with meeting unknown people in unknown locations.</p>
			</div>
		</div>
		<div class="benflpboxiner">
			<div class="benflpboxiner_icon">
				<img src="{{ asset('assets/svg/time-icon.svg') }}" alt="">
			</div>
			<div class="benflpboxiner_text">
				<h4>Time</h4>
				<p>Posting your vehicle with FlipQuick saves both effort and time. It eliminates the need for several private showings as well as transportation between multiple dealerships. It is physically impossible to meet with every dealership that FlipQuick gives you access to, especially within 24 hours.</p>
			</div>
		</div>
		<div class="benflpboxiner">
			<div class="benflpboxiner_icon">
				<img src="{{ asset('assets/svg/value-icon.svg') }}" alt="">
			</div>
			<div class="benflpboxiner_text">
				<h4>Value</h4>
				<p>Dealerships are given the opportunity to place only one offer on your vehicle. Since they are competing with eachother, they will only give you their best offer. This saves you the process of negotiating, and connects you directly to the dealership willing to pay you the most for your vehicle.</p>
			</div>
		</div>
		<div class="benflpboxiner">
			<div class="benflpboxiner_icon">
				<img src="{{ asset('assets/svg/pro-icon.svg') }}" alt="">
			</div>
			<div class="benflpboxiner_text">
				<h4>Become a pro</h4>
				<p>Our app guides you through what information is required for dealerships to accurately evaluate your vehicle.</p>
			</div>
		</div>
	</div>
	

	<div class="aryodealcover">
		<div class="aryodealbox_left">
			<h3>Are you a Dealership 
				looking to buy vehicles 
			from local sellers?</h3>
			<p>Get started with FlipQuick to view daily vehicle listings. Submit your best bid and start buying!</p>
			<a href="{{ route('website.dealer.signup') }}">GET STARTED</a>
		</div>
		<div class="aryodealbox_right">
			<img src="{{ asset('assets/images/flipquick_dealership_car.png') }}" alt="">		
		</div>
	</div>
</div>

@include('website.layouts.footer')


@endsection

@section('scripts')

@endsection

resources/views/website/pricing.blade.php
@section('title','FlipQuick | Signup')
@extends('website.layouts.app')
@section('styles')
<style type="text/css">
	.cretact_title {
    padding-bottom: 20px;
}
.pricingboxcover {
    max-width: 50%;
}
.box3 h3 {
    color: #01034A;
    min-height: 56px;
}
.box2 h3 {
    color: #FF6600;
    min-height: 31px;
}
</style>
@endsection
@section('content')
<div class="container">
	<div class="cretactbox pricingshowpage">

<div class="pricingboxcover">
	<!-- <div class="radio">
		<div class="pricingboxiner box1">
			<h3>FREE</h3>
			<p>30 days trial</p>
			<hr>
			<input id="radio-1" name="radio" type="radio" checked>
			<label for="radio-1" class="radio-label"></label>
		</div>
	</div> -->
<ul class="tabs">
					<li><a href="javascript:void(0);" rel="#tabcontent1" class="tab active">I'm a Dealership</a></li>
					<li><a href="javascript:void(0);" rel="#tabcontent2" class="tab">I'm a Seller</a></li>	       
				</ul>	    
				<div class="tab_content_container">
					<div class="tab_content tab_content_active" id="tabcontent1">
								<div class="cretact_title">
<!-- 			<h3>Hello</h3>
-->			<p>Here are the two types of membership plans to fit your needs!</p>
</div>
						<div class="radio">
							<div class="pricingboxiner box2">	
								<h3>$500 </h3>
								<h3>Unlimited Bid Winning Package. </h3>
								<p>Bid on, and win unlimited vehicles for one monthly fee (Recommended) </p>
								<hr>
								<!-- <span>FULL PRICE</span> -->
								<input id="radio-2" name="radio" type="radio">
								<label  for="radio-2" class="radio-label"></label>
							</div>
						</div>
						<div class="radio">
							<div class="pricingboxiner box3">
								<h3>$50 </h3>
								<h3>Pay per Win Package</h3>
								<p>Bid on unlimited vehicles but pay a fee for each vehicle you win.</p>
								<hr>
								<!-- <span>FULL PRICE</span> -->
								<input id="radio-3" name="radio" type="radio">
								<label  for="radio-3" class="radio-label"></label>
							</div>
						</div>
						<div class="veriemailbtn">
	<a href="{{route('website.dealer.signup')}}">COUNTINUE</a>
</div>
					</div>
					<div class="tab_content" id="tabcontent2">
						<div class="radio" style="margin-top: 50px;">
							<div class="pricingboxiner box2">	
								<p>Posting your vehicle with FlipQuick is absolutely free!</p>
								<hr>
								<!-- <span>FULL PRICE</span> -->
								<!-- <input id="radio-2" name="radio" type="radio">
								<label  for="radio-2" class="radio-label"></label> -->
							</div>
						</div>
					</div>
				</div>	
</div>

</div>
</div>


@include('website.layouts.footer')



@endsection

@section('scripts')
<script>
	$(document).ready(function(){
		$(".tabs li a").click(function() {
			
			// Active state for tabs
			$(".tabs li a").removeClass("active");
			$(this).addClass("active");
			
			// Active state for Tabs Content
			$(".tab_content_container > .tab_content_active").removeClass("tab_content_active").fadeOut(200);
			$(this.rel).fadeIn(500).addClass("tab_content_active");
			
		});	

	});

</script>
@endsection